---
abstract: 'Garbage in, goodness out'
author:
  - 'Trevor S. Cornpropst <tscornpropst@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.63'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.142060'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Str-Filter
no_index:
  directory:
    - t
    - inc
requires:
  HTML::Strip: '0'
  perl: '5.006'
version: '0.01'
